randomStringMyApi/Models/ErrorViewModel.cs
namespace randomStringMyApi.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

randomStringMyApi/Models/StringsModel.cs
using System;

namespace randomStringMyApi.Models
{
	public class StringsModel
	{
		public string[] Strings { get; set; }
		public int Count { get; set; }
		public int Length { get; set; }
		public StringsModel(int count, int length)
		{
			Count = count;
			Length = length;
			Strings = new string[count];
		}
		public void RandomString(int count, int length)
		{
			Random random= new Random();
			const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
			for (int i = 0; i < count; i++)
			{
				string k = new string(Enumerable.Repeat(chars, length)
				.Select(s => s[random.Next(s.Length)]).ToArray());
				Strings[i] = k;
			}
		}
	}
}

randomStringMyApi/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using randomStringMyApi.Models;
using System.Diagnostics;

namespace randomStringMyApi.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}
		public IActionResult ToString()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

randomStringMyApi/Controllers/RandomController.cs
using Microsoft.AspNetCore.Mvc;
using randomStringMyApi.Models;

namespace randomStringMyApi.Controllers
{
	public class RandomController : Controller
	{
		public async Task<IActionResult> Index(int Count, int Length)
		{
			HttpClient client = new HttpClient();
			string baseString = $"https://localhost:7075/api/Strings/count={Count}&length={Length}";
			HttpResponseMessage response = await client.GetAsync(baseString);
			response.EnsureSuccessStatusCode();
			string responseBody = await response.Content.ReadAsStringAsync();
			StringsModel stringsModel = System.Text.Json.JsonSerializer.Deserialize<StringsModel>(responseBody)!;
			return View(stringsModel);
		}
	}
}

randomStringMyApi/Controllers/StringsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.ObjectPool;
using Newtonsoft.Json.Linq;
using randomStringMyApi.Models;
using System;
using System.Reflection.Metadata.Ecma335;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using static System.Net.Mime.MediaTypeNames;

namespace randomStringMyApi.Controllers
{
	[Route("api/strings/{id}")]
	[ApiController]
	public class StringsController : ControllerBase
	{
		[HttpGet]
		public string GetStrings(string id)
		{
			string[] targetStrings = id.Split("&"); 
			int count = int.Parse(Regex.Match(targetStrings[0], @"([0-9 ]+)").Value);
			int length = int.Parse(Regex.Match(targetStrings[1], @"([0-9 ]+)").Value);
			StringsModel model = new StringsModel(count, length);
			model.RandomString(count, length);
			string jsonString = JsonSerializer.Serialize(model);
			return jsonString;
		}
	}
}

randomStringMyApi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

randomStringMyApi/Views/Home/ToString.cshtml
<form method="post" asp-controller="Random" asp-action="Index">
	<table>
		<tr>
			<td><p>Количество строк</p></td>
			<td><input id="Count" type="number" name="Count" /> </td>
		</tr>
		<tr>
			<td><p>Длина строк</p></td>
			<td><input id="Length" type="number" name="Length" /> </td>
		</tr>
	</table>
	<input type="submit" value="Получить строки" />
</form>

randomStringMyApi/Views/Random/Index.cshtml
@model randomStringMyApi.Models.StringsModel
@{
	ViewData["Title"] = "Home Page";
	var strings = Model;
}

<div class="text-center">
	<a asp-controller="Home" asp-action="ToString">Назад</a>
	@if (Model != null)
	{
		@for (int i = 0; i < Model.Count; i++)
		{
			<h1 class="display-4">@Model.Strings[i]</h1>
		}
	}
</div>

randomStringMyApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - randomStringMyApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/randomStringMyApi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">randomStringMyApi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ToStrings">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - randomStringMyApi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>